#!/usr/bin/env bash
set -euo pipefail

readonly STABLE_BRANCH="main"
readonly RELEASE_TYPE="${1:-}"

fail() {
  echo "Error: $*" >&2
  exit 1
}

usage() {
  cat >&2 <<'EOF'
Usage: scripts/release.sh init|patch|rc|rc:minor|rc:major|rc:promote
EOF
  exit 1
}

package_version() {
  node -e 'const p=require("./package.json"); if(typeof p.version!=="string") process.exit(1); process.stdout.write(p.version)'
}

stable_version() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

rc_version() {
  [[ "$1" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-rc\.([1-9][0-9]*)$ ]]
}

next_version() {
  local version="$1"
  local kind="$2"
  node -e '
    const [version, kind] = process.argv.slice(1);
    const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
    if (!match) process.exit(1);
    let [, major, minor, patch] = match.map(Number);
    if (kind === "patch") patch += 1;
    else if (kind === "minor") { minor += 1; patch = 0; }
    else if (kind === "major") { major += 1; minor = 0; patch = 0; }
    else process.exit(1);
    process.stdout.write(`${major}.${minor}.${patch}`);
  ' "$version" "$kind"
}

remote_ref_exists() {
  local kind="$1"
  local name="$2"
  local status
  if git ls-remote --exit-code "--${kind}" origin "refs/${kind}/${name}" >/dev/null 2>&1; then
    return 0
  else
    status=$?
  fi
  [[ "$status" -eq 2 ]] && return 1
  fail "unable to inspect remote ${kind%?} '${name}'."
}

ensure_branch_available() {
  local branch="$1"
  git show-ref --verify --quiet "refs/heads/${branch}" && fail "local branch '${branch}' already exists."
  remote_ref_exists heads "$branch" && fail "remote branch '${branch}' already exists."
  return 0
}

ensure_tag_available() {
  local tag="$1"
  git show-ref --verify --quiet "refs/tags/${tag}" && fail "local tag '${tag}' already exists."
  remote_ref_exists tags "$tag" && fail "remote tag '${tag}' already exists."
  return 0
}

stage_package_metadata() {
  local files=(package.json)
  [[ -f package-lock.json ]] && files+=(package-lock.json)
  git add -- "${files[@]}" || return 1
  if git diff --cached --quiet; then
    echo "Error: npm version produced no package metadata change." >&2
    return 1
  fi
}

set_package_version() {
  local version="$1"
  npm version "$version" --no-git-tag-version --ignore-scripts >/dev/null || return 1
  if [[ "$(package_version)" != "$version" ]]; then
    echo "Error: package.json version is not '${version}' after npm version." >&2
    return 1
  fi
  if [[ -f package-lock.json ]]; then
    if [[ "$(node -p "require('./package-lock.json').version")" != "$version" ]]; then
      echo "Error: package-lock.json version is not '${version}'." >&2
      return 1
    fi
    if [[ "$(node -p "require('./package-lock.json').packages?.['']?.version || ''")" != "$version" ]]; then
      echo "Error: package-lock.json root package version is not '${version}'." >&2
      return 1
    fi
  fi
}

write_tag_output() {
  local tag="$1"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf 'tag=%s\n' "$tag" >>"$GITHUB_OUTPUT"
  fi
}

validate_rc_context() {
  local branch="$1"
  local version="$2"
  local branch_base
  local package_base

  [[ "$branch" =~ ^rc/v([0-9]+\.[0-9]+\.[0-9]+)-rc\.1$ ]] || fail "'${RELEASE_TYPE}' must run on branch 'rc/vX.Y.Z-rc.1' (current: '${branch}')."
  branch_base="${BASH_REMATCH[1]}"
  rc_version "$version" || fail "package version '${version}' is not an RC version."
  package_base="${BASH_REMATCH[1]}"
  [[ "$branch_base" == "$package_base" ]] || fail "RC branch base '${branch_base}' does not match package base '${package_base}'."
}

existing_release_pr() {
  local release_branch="$1"
  gh pr list \
    --base "$STABLE_BRANCH" \
    --head "$release_branch" \
    --state open \
    --json url \
    --jq '.[0].url // empty'
}

create_release_pr() {
  local release_branch="$1"
  local target_version="$2"
  local pr_url

  pr_url="$(existing_release_pr "$release_branch")" || fail "gh failed to inspect existing PRs for '${release_branch}'."
  if [[ -z "$pr_url" ]]; then
    if ! pr_url=$(gh pr create \
      --base "$STABLE_BRANCH" \
      --head "$release_branch" \
      --title "chore: release v${target_version}" \
      --body "Release v${target_version} generated by scripts/release.sh.

This PR contains the version bump. Tag creation happens after merge into main."); then
      pr_url="$(existing_release_pr "$release_branch")" || fail "gh failed to verify PR state after create failure for '${release_branch}'."
      [[ -n "$pr_url" ]] || fail "gh failed to create PR '${release_branch}' -> '${STABLE_BRANCH}'. Branch remains pushed for recovery."
    fi
  fi
  [[ -n "$pr_url" ]] || fail "gh returned success without a PR URL for '${release_branch}'."
  echo "PR created: ${pr_url}"
}

release_version_at_ref() {
  local ref="$1"
  local path="$2"
  git show "${ref}:${path}" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).version || ""))'
}

validate_release_recovery_ref() {
  local ref="$1"
  local source_head="$2"
  local target_version="$3"
  local expected="package.json"
  local actual
  local parents

  read -r -a parents <<<"$(git rev-list --parents -n 1 "$ref")"
  [[ "${#parents[@]}" -eq 2 && "${parents[1]}" == "$source_head" ]] || fail "recovery branch '${ref}' must be one commit directly above the current source commit."

  if git cat-file -e "${source_head}:package-lock.json" 2>/dev/null; then
    expected=$'package-lock.json\npackage.json'
  fi
  actual="$(git diff --name-only "$source_head" "$ref" | sort)"
  [[ "$actual" == "$expected" ]] || fail "recovery branch '${ref}' contains changes outside expected package metadata."

  [[ "$(release_version_at_ref "$ref" package.json)" == "$target_version" ]] || fail "recovery branch '${ref}' has the wrong package version."
  if [[ "$expected" == *package-lock.json* ]]; then
    [[ "$(release_version_at_ref "$ref" package-lock.json)" == "$target_version" ]] || fail "recovery branch '${ref}' has the wrong lockfile version."
    [[ "$(git show "${ref}:package-lock.json" | node -e 'let s=""; process.stdin.on("data", d => s += d).on("end", () => process.stdout.write(JSON.parse(s).packages?.[""]?.version || ""))')" == "$target_version" ]] || fail "recovery branch '${ref}' has the wrong lockfile root package version."
  fi
}

create_release_pr_branch() {
  local current_version="$1"
  local target_version="$2"
  local source_branch="$3"
  local source_head
  local release_branch="release/v${target_version}"
  local remote_ref="refs/remotes/origin/${release_branch}"

  command -v gh >/dev/null 2>&1 || fail "GitHub CLI (gh) is required to create the release PR."
  ensure_tag_available "v${target_version}"
  source_head="$(git rev-parse HEAD)"

  if remote_ref_exists heads "$release_branch"; then
    git fetch --quiet origin "refs/heads/${release_branch}:${remote_ref}" || fail "failed to fetch recovery branch '${release_branch}'."
    validate_release_recovery_ref "$remote_ref" "$source_head" "$target_version"
    create_release_pr "$release_branch" "$target_version"
    return
  fi

  if git show-ref --verify --quiet "refs/heads/${release_branch}"; then
    validate_release_recovery_ref "$release_branch" "$source_head" "$target_version"
    if ! git push origin "refs/heads/${release_branch}:refs/heads/${release_branch}" >/dev/null; then
      fail "failed to push '${release_branch}'. Local branch remains for recovery."
    fi
    create_release_pr "$release_branch" "$target_version"
    return
  fi

  git switch -c "$release_branch" >/dev/null
  if ! set_package_version "$target_version" || ! stage_package_metadata ||
    ! git commit -m "chore: release v${target_version}" >/dev/null; then
    git reset --hard "$source_head" >/dev/null 2>&1 || true
    git switch "$source_branch" >/dev/null 2>&1 || true
    git branch -D "$release_branch" >/dev/null 2>&1 || true
    fail "failed to create '${release_branch}' from version '${current_version}'."
  fi
  if ! git push origin "refs/heads/${release_branch}:refs/heads/${release_branch}" >/dev/null; then
    git switch "$source_branch" >/dev/null 2>&1 || true
    fail "failed to push '${release_branch}'. Local branch remains for recovery."
  fi

  git switch "$source_branch" >/dev/null
  create_release_pr "$release_branch" "$target_version"
}

start_rc_train() {
  local kind="${RELEASE_TYPE#rc:}"
  local base
  local version
  local branch
  local tag
  local start_head="$5"

  base="$(next_version "$1" "$kind")" || fail "cannot calculate next ${kind} version from '${1}'."
  version="${base}-rc.1"
  branch="rc/v${base}-rc.1"
  tag="v${version}"
  ensure_branch_available "$branch"
  ensure_tag_available "$tag"

  git switch -c "$branch" >/dev/null
  if ! set_package_version "$version" || ! stage_package_metadata ||
    ! git commit -m "chore: release ${tag}" >/dev/null ||
    ! git tag "$tag" ||
    ! git push --atomic origin "refs/heads/${branch}:refs/heads/${branch}" "refs/tags/${tag}:refs/tags/${tag}" >/dev/null; then
    git tag -d "$tag" >/dev/null 2>&1 || true
    git reset --hard "$start_head" >/dev/null 2>&1 || true
    git switch "$STABLE_BRANCH" >/dev/null 2>&1 || true
    git branch -D "$branch" >/dev/null 2>&1 || true
    fail "failed to create RC branch and tag atomically."
  fi

  write_tag_output "$tag"
  echo "Pushed ${branch} and ${tag}"
}

increment_rc() {
  local current="$1"
  local branch="$2"
  local start_head="$3"
  local base
  local number
  local version
  local tag

  rc_version "$current"
  base="${BASH_REMATCH[1]}"
  number="${BASH_REMATCH[2]}"
  version="${base}-rc.$((number + 1))"
  tag="v${version}"
  ensure_tag_available "$tag"

  if ! set_package_version "$version" || ! stage_package_metadata ||
    ! git commit -m "chore: release ${tag}" >/dev/null ||
    ! git tag "$tag" ||
    ! git push --atomic origin "refs/heads/${branch}:refs/heads/${branch}" "refs/tags/${tag}:refs/tags/${tag}" >/dev/null; then
    git tag -d "$tag" >/dev/null 2>&1 || true
    git reset --hard "$start_head" >/dev/null 2>&1 || true
    fail "failed to push RC branch and tag atomically."
  fi

  write_tag_output "$tag"
  echo "Pushed ${tag} from ${branch}"
}

case "$RELEASE_TYPE" in
init | patch | rc | rc:minor | rc:major | rc:promote) ;;
*) usage ;;
esac

for command in git node npm; do
  command -v "$command" >/dev/null 2>&1 || fail "required command '${command}' was not found."
done
[[ -f package.json ]] || fail "package.json was not found."
[[ -z "$(git status --porcelain)" ]] || fail "working tree and index must be clean."
git remote get-url origin >/dev/null 2>&1 || fail "git remote 'origin' is required."
git fetch --quiet --prune --tags origin || fail "failed to fetch origin."

CURRENT_BRANCH="$(git branch --show-current)"
[[ -n "$CURRENT_BRANCH" ]] || fail "unable to determine current branch."
CURRENT_VERSION="$(package_version)" || fail "unable to read package.json version."
START_HEAD="$(git rev-parse HEAD)"

case "$RELEASE_TYPE" in
init | patch | rc:minor | rc:major)
  [[ "$CURRENT_BRANCH" == "$STABLE_BRANCH" ]] || fail "'${RELEASE_TYPE}' must run on '${STABLE_BRANCH}' (current: '${CURRENT_BRANCH}')."
  [[ "$(git rev-parse HEAD)" == "$(git rev-parse refs/remotes/origin/main)" ]] || fail "'main' must be aligned with 'origin/main'."
  stable_version "$CURRENT_VERSION" || fail "package version '${CURRENT_VERSION}' must be stable."
  ;;
rc | rc:promote)
  validate_rc_context "$CURRENT_BRANCH" "$CURRENT_VERSION"
  [[ "$(git rev-parse HEAD)" == "$(git rev-parse "refs/remotes/origin/${CURRENT_BRANCH}")" ]] || fail "'${CURRENT_BRANCH}' must be aligned with 'origin/${CURRENT_BRANCH}'."
  ;;
esac

case "$RELEASE_TYPE" in
init)
  [[ "${CONFIRM_INIT:-}" == "yes" ]] || fail "init requires CONFIRM_INIT=yes."
  [[ -z "$(git tag --list 'v*')" ]] || fail "init is blocked because a local v* tag exists."
  [[ -z "$(git ls-remote --tags origin 'refs/tags/v*')" ]] || fail "init is blocked because a remote v* tag exists."
  TAG="v${CURRENT_VERSION}"
  git tag "$TAG"
  if ! git push origin "refs/tags/${TAG}:refs/tags/${TAG}" >/dev/null; then
    git tag -d "$TAG" >/dev/null 2>&1 || true
    fail "failed to push '${TAG}'."
  fi
  write_tag_output "$TAG"
  echo "Pushed initial tag ${TAG}"
  ;;
patch)
  TARGET_VERSION="$(next_version "$CURRENT_VERSION" patch)" || fail "cannot calculate patch version."
  create_release_pr_branch "$CURRENT_VERSION" "$TARGET_VERSION" "$CURRENT_BRANCH"
  ;;
rc:minor | rc:major)
  start_rc_train "$CURRENT_VERSION" "$CURRENT_BRANCH" "$RELEASE_TYPE" "$STABLE_BRANCH" "$START_HEAD"
  ;;
rc)
  increment_rc "$CURRENT_VERSION" "$CURRENT_BRANCH" "$START_HEAD"
  ;;
rc:promote)
  rc_version "$CURRENT_VERSION"
  TARGET_VERSION="${BASH_REMATCH[1]}"
  create_release_pr_branch "$CURRENT_VERSION" "$TARGET_VERSION" "$CURRENT_BRANCH"
  ;;
esac
